name: kcs_2020_shinkan_web
description: Keio Computer Society 2020年度新歓特設ページです！
version: 1.3.4

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_localizations:
    sdk: flutter
  expandable: ^4.1.2
  auto_size_text: ^2.1.0
  responsive_grid: ^1.1.1
  url_launcher: ^5.4.2
  easy_web_view: ^1.1.1
  firebase: ^7.2.1
  fb_auth:
    git:
      url: git://github.com/organic-nailer/fb_auth.git
      ref: master
  clippy_flutter: ^1.1.1
  expanded_grid: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - image/kcsdragon.png
    - image/yuzuka.jpg
    - image/yuzuka_rough.jpg
    - image/kcschann.png
    - image/topbackground.jpg
    - image/top_ai.png
    - image/top_blender.png
    - image/top_dtm.png
    - image/top_unity.png
    - image/top_web.png
    - image/kcslogo.png
    - image/groupintroduce.jpg
    - image/events.jpg
    - image/twitterlogo.png
    - image/githublogo.png
    - image/kcsdragonlogo.png
    - image/fastlogo.png
    - image/orfevrelogo.jpg
    - image/atsumori.jpg
    - image/beyondthelimit.jpg
    - image/tsuratan.jpg
    - image/characters.jpg
    - image/linelogo.png
    - image/kcschann_standing.png
    - image/groups/ai.jpg
    - image/groups/blender.jpg
    - image/groups/dtm.jpg
    - image/groups/yunity.jpg
    - image/groups/web.jpg
    - image/icon_qrcode.png
    - image/schedule/
    - image/works/

  fonts:
    - family: CorporateLogo
      fonts:
        - asset: fonts/corporate_logo_bold.ttf
    - family: MPlus
      fonts:
        - asset: fonts/mplus_2p_light.ttf
          weight: 300
        - asset: fonts/mplus_2p_regular.ttf
          weight: 400
        - asset: fonts/mplus_2p_bold.ttf
          weight: 700
    - family: Anzu
      fonts:
        - asset: fonts/anzumoji.ttf
